version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bawuiacademy
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/bawuiacademy
      NEXTAUTH_URL: http://localhost:3002
      NEXTAUTH_SECRET: dev-secret-change-in-production
      NEXT_PUBLIC_APP_URL: http://localhost:3002
      AUTH_TRUST_HOST: "true"
      AUTH_SECRET: dev-secret-change-in-production
      NODE_V8_FLAGS: "--no-opt --no-turboshaft"
    depends_on:
      - db



volumes:
  pgdata:
